spring.application.name=graphql-playground

# graphql
spring.graphql.schema.locations=classpath:graphql/lec16
spring.graphql.path=/graphql
spring.graphql.websocket.path=/graphql

# graphiql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

customer.service.url=http://localhost:8080/graphql