spring.application.name=graphql-playground

# graphql
spring.graphql.schema.locations=classpath:graphql/sec01/lec02
spring.graphql.path=/graphql

# graphiql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql